/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carsalemanagement;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author Dell
 */
public class Enter extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     * */
     ResultSet rs,rs_regno,rs_id;
    PreparedStatement pst,pst_regno,pst_id;
    Connection con = null;
    public Enter() {
        initComponents();
        createConnection();
        
        FontStyle(regnot);
        FontStyle(maket);
        FontStyle(manuyt);
        FontStyle(regyt);
        FontStyle(milaget);
        FontStyle2(refnot);
        FontStyle2(tpt);
        FontStyle2(datet);
    }
    public void autorefNo(){
         try {
             Statement s = con.createStatement();
             ResultSet rs = s.executeQuery("Select Max(RefNo) from enter ");
             rs.next();
             
             rs.getString("Max(RefNo)");
             
             if(rs.getString("Max(RefNo)")==null){
                 refnot.setText("C0001");
             }
             else{
                 Long RefNo= Long.parseLong(rs.getString("Max(RefNo)").substring(2,rs.getString("Max(RefNo)").length()));
                 RefNo++;
                 refnot.setText("C0" + String.format("%03d", RefNo));
             }
         } catch (SQLException ex) {
             Logger.getLogger(Enter.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void FontStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.white);
         
    }

    public void FontStyle2(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.LIGHT_GRAY);
         
    }
    
    void createConnection(){
        String className = "com.mysql.cj.jdbc.Driver";
        try {
            Class.forName(className);
            System.out.println("Driver loaded Successfully");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/abc","root","root");
            System.out.println("Connection Successfull");
      
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver loding Failed");
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
            System.out.println("Connection Failed");
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        regnot = new javax.swing.JTextField();
        categoryt = new javax.swing.JTextField();
        maket = new javax.swing.JTextField();
        modelt = new javax.swing.JTextField();
        manuyt = new javax.swing.JTextField();
        regyt = new javax.swing.JTextField();
        milaget = new javax.swing.JTextField();
        pricet = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        nict = new javax.swing.JTextField();
        namet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresst = new javax.swing.JTextArea();
        tpt = new javax.swing.JTextField();
        datet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        refnot = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reftext = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 31, 61));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reg. No.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Make");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Model");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manu. Year");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reg. Year");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Milage");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        regnot.setBackground(new java.awt.Color(73, 31, 61));
        regnot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regnot.setForeground(new java.awt.Color(255, 255, 255));
        regnot.setText("XXX-xxx");
        regnot.setToolTipText("");
        regnot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        regnot.setCaretColor(new java.awt.Color(255, 255, 255));
        regnot.setMinimumSize(new java.awt.Dimension(7, 21));
        regnot.setPreferredSize(new java.awt.Dimension(7, 21));
        regnot.setSelectionColor(new java.awt.Color(255, 255, 255));
        regnot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regnotFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regnotFocusLost(evt);
            }
        });
        regnot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regnotMouseClicked(evt);
            }
        });
        regnot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regnotKeyPressed(evt);
            }
        });
        jPanel1.add(regnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, -1));

        categoryt.setBackground(new java.awt.Color(73, 31, 61));
        categoryt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryt.setForeground(new java.awt.Color(255, 255, 255));
        categoryt.setToolTipText("");
        categoryt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        categoryt.setCaretColor(new java.awt.Color(255, 255, 255));
        categoryt.setPreferredSize(new java.awt.Dimension(7, 21));
        categoryt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categorytKeyPressed(evt);
            }
        });
        jPanel1.add(categoryt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));

        maket.setBackground(new java.awt.Color(73, 31, 61));
        maket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maket.setForeground(new java.awt.Color(153, 153, 153));
        maket.setText("YYYY");
        maket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        maket.setCaretColor(new java.awt.Color(255, 255, 255));
        maket.setPreferredSize(new java.awt.Dimension(7, 21));
        maket.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maketFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                maketFocusLost(evt);
            }
        });
        maket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maketActionPerformed(evt);
            }
        });
        maket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maketKeyPressed(evt);
            }
        });
        jPanel1.add(maket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 190, -1));

        modelt.setBackground(new java.awt.Color(73, 31, 61));
        modelt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelt.setForeground(new java.awt.Color(255, 255, 255));
        modelt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        modelt.setCaretColor(new java.awt.Color(255, 255, 255));
        modelt.setPreferredSize(new java.awt.Dimension(7, 21));
        modelt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modeltKeyPressed(evt);
            }
        });
        jPanel1.add(modelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 190, -1));

        manuyt.setBackground(new java.awt.Color(73, 31, 61));
        manuyt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manuyt.setForeground(new java.awt.Color(153, 153, 153));
        manuyt.setText("YYYY");
        manuyt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        manuyt.setCaretColor(new java.awt.Color(255, 255, 255));
        manuyt.setPreferredSize(new java.awt.Dimension(7, 21));
        manuyt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manuytFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                manuytFocusLost(evt);
            }
        });
        manuyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuytActionPerformed(evt);
            }
        });
        manuyt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manuytKeyPressed(evt);
            }
        });
        jPanel1.add(manuyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 190, -1));

        regyt.setBackground(new java.awt.Color(73, 31, 61));
        regyt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regyt.setForeground(new java.awt.Color(153, 153, 153));
        regyt.setText("YYYY");
        regyt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        regyt.setCaretColor(new java.awt.Color(255, 255, 255));
        regyt.setPreferredSize(new java.awt.Dimension(7, 21));
        regyt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regytFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regytFocusLost(evt);
            }
        });
        regyt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                regytKeyPressed(evt);
            }
        });
        jPanel1.add(regyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 190, -1));

        milaget.setBackground(new java.awt.Color(73, 31, 61));
        milaget.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        milaget.setForeground(new java.awt.Color(153, 153, 153));
        milaget.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        milaget.setCaretColor(new java.awt.Color(255, 255, 255));
        milaget.setPreferredSize(new java.awt.Dimension(7, 21));
        milaget.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                milagetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                milagetFocusLost(evt);
            }
        });
        milaget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                milagetKeyPressed(evt);
            }
        });
        jPanel1.add(milaget, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 190, -1));

        pricet.setBackground(new java.awt.Color(73, 31, 61));
        pricet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pricet.setForeground(new java.awt.Color(255, 255, 255));
        pricet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pricet.setCaretColor(new java.awt.Color(255, 255, 255));
        pricet.setPreferredSize(new java.awt.Dimension(7, 21));
        pricet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pricetKeyPressed(evt);
            }
        });
        jPanel1.add(pricet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 190, -1));

        jLabel13.setFont(new java.awt.Font("Tekton Pro Ext", 0, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ABC");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Vehicle  ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        text1.setBackground(new java.awt.Color(73, 31, 61));
        text1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 204, 204));
        text1.setBorder(null);
        jPanel1.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 135, 190, 10));

        text3.setBackground(new java.awt.Color(73, 31, 61));
        text3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 204, 204));
        text3.setBorder(null);
        jPanel1.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 215, 190, 10));

        text5.setBackground(new java.awt.Color(73, 31, 61));
        text5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 204, 204));
        text5.setBorder(null);
        jPanel1.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 295, 190, 10));

        text6.setBackground(new java.awt.Color(73, 31, 61));
        text6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text6.setForeground(new java.awt.Color(255, 204, 204));
        text6.setBorder(null);
        jPanel1.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 335, 190, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        jPanel2.setBackground(new java.awt.Color(189, 76, 84));
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText(" Home ");
        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText(" Save ");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        nict.setBackground(new java.awt.Color(189, 76, 84));
        nict.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nict.setForeground(new java.awt.Color(255, 255, 255));
        nict.setToolTipText("");
        nict.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        nict.setCaretColor(new java.awt.Color(255, 255, 255));
        nict.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nictKeyPressed(evt);
            }
        });
        jPanel2.add(nict, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));

        namet.setBackground(new java.awt.Color(189, 76, 84));
        namet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namet.setForeground(new java.awt.Color(255, 255, 255));
        namet.setToolTipText("");
        namet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        namet.setCaretColor(new java.awt.Color(255, 255, 255));
        namet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametActionPerformed(evt);
            }
        });
        namet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametKeyPressed(evt);
            }
        });
        jPanel2.add(namet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 20));

        addresst.setBackground(new java.awt.Color(189, 76, 84));
        addresst.setColumns(20);
        addresst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addresst.setForeground(new java.awt.Color(255, 255, 255));
        addresst.setLineWrap(true);
        addresst.setRows(1);
        addresst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addresst.setCaretColor(new java.awt.Color(255, 255, 255));
        addresst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addresstKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(addresst);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 250, 70));

        tpt.setBackground(new java.awt.Color(189, 76, 84));
        tpt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpt.setForeground(new java.awt.Color(204, 204, 204));
        tpt.setText("077-1234567");
        tpt.setToolTipText("");
        tpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tpt.setCaretColor(new java.awt.Color(255, 255, 255));
        tpt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tptFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tptFocusLost(evt);
            }
        });
        tpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tptActionPerformed(evt);
            }
        });
        tpt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tptKeyPressed(evt);
            }
        });
        jPanel2.add(tpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 250, 20));

        datet.setBackground(new java.awt.Color(189, 76, 84));
        datet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datet.setForeground(new java.awt.Color(204, 204, 204));
        datet.setText("YYYY-MM-DD");
        datet.setToolTipText("");
        datet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        datet.setCaretColor(new java.awt.Color(255, 255, 255));
        datet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                datetFocusLost(evt);
            }
        });
        datet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetActionPerformed(evt);
            }
        });
        datet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datetKeyPressed(evt);
            }
        });
        jPanel2.add(datet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 190, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIC");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Address");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Telephone");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Date");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("Owner  ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        refnot.setBackground(new java.awt.Color(189, 76, 84));
        refnot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refnot.setForeground(new java.awt.Color(204, 204, 204));
        refnot.setText("0000");
        refnot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        refnot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                refnotFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                refnotFocusLost(evt);
            }
        });
        refnot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                refnotKeyPressed(evt);
            }
        });
        jPanel2.add(refnot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ref. No.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 20));

        reftext.setBackground(new java.awt.Color(189, 76, 84));
        reftext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reftext.setForeground(new java.awt.Color(255, 204, 204));
        reftext.setBorder(null);
        jPanel2.add(reftext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 10));

        text7.setBackground(new java.awt.Color(189, 76, 84));
        text7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text7.setForeground(new java.awt.Color(255, 204, 204));
        text7.setBorder(null);
        jPanel2.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 250, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, 450));
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametActionPerformed

    private void tptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tptActionPerformed

    private void maketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maketActionPerformed

    private void datetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetActionPerformed
    
    public void savevehicle(){
        //For vehicles
        String regno = regnot.getText();
        String category = categoryt.getText();
        String make = maket.getText();
        String model = modelt.getText();
        String manuy = manuyt.getText();
        String regy = regyt.getText();
        String milage = milaget.getText();
        String price = pricet.getText();
        
        //For owners
        String refno = refnot.getText();
        String nic = nict.getText();
        String name = namet.getText();
        String address = addresst.getText();
        String tp = tpt.getText();
        String date = datet.getText();
        String regno1 = regnot.getText();
        String status = "Available";
        try {
            if(refno.equals("") || nic.equals("") || name.equals("") || address.equals("") || tp.equals("")
                        || date.equals("") || regno1.equals("") || category.equals("") || make.equals("") || model.equals("") || manuy.equals("") ||regy.equals("") || milage.equals("") || price.equals(""))
             {
                    JOptionPane.showMessageDialog(this,"All required fields are mandatory"); 
              }
            else{
                pst_regno = con.prepareStatement("SELECT * from vehicle WHERE RegNo=?");
                pst_regno.setString(1,regnot.getText());
                rs_regno = pst_regno.executeQuery();
                
                pst_id = con.prepareStatement("SELECT * from owner WHERE NIC=?");
                pst_id.setString(1,nict.getText());
                rs_id = pst_id.executeQuery();
                
                int OwnerStatus = 1;
                int VehicleStatus = 1;
                if(rs_regno.next()==false){
                    VehicleStatus = 0;
                }
                if(rs_id.next()==false){
                    OwnerStatus = 0;
                }
                
                Statement stm = con.createStatement();
                if(VehicleStatus == 0 && OwnerStatus == 0){
                    String sql_owner ="INSERT INTO owner VALUES('"+nic+"','"+name+"','"+address+"','"+tp+"')";
                    String sql_vehicle ="INSERT INTO vehicle VALUES('"+regno+"','"+make+"','"+model+"','"+manuy+"','"+regy+"','"+category+"','"+status+"')";
                    stm.executeUpdate(sql_owner);
                    stm.executeUpdate(sql_vehicle);
                }else{
                    if(VehicleStatus == 0 && OwnerStatus == 1){
                        String sql_owner = "UPDATE owner SET Name = '"+name+"',Address = '"+address+"',Tele = '"+tp+"' WHERE NIC = '"+nic+"'";
                        String sql_vehicle ="INSERT INTO vehicle VALUES('"+regno+"','"+make+"','"+model+"','"+manuy+"','"+regy+"','"+category+"','"+status+"')";
                        stm.executeUpdate(sql_vehicle);
                        stm.executeUpdate(sql_owner);
                    }else{
                        if(VehicleStatus == 1 && OwnerStatus == 0){
                            String sql_vehicle = "UPDATE vehicle SET Status = '"+status+"' WHERE RegNo = '"+regno+"'";
                            String sql_owner ="INSERT INTO owner VALUES('"+nic+"','"+name+"','"+address+"','"+tp+"')";
                            stm.executeUpdate(sql_owner);
                            stm.executeUpdate(sql_vehicle);
                        }else{
                            String sql_owner = "UPDATE owner SET Name = '"+name+"',Address = '"+address+"',Tele = '"+tp+"' WHERE NIC = '"+nic+"'";
                            String sql_vehicle = "UPDATE vehicle SET Status = '"+status+"' WHERE RegNo = '"+regno+"'";
                            stm.executeUpdate(sql_owner);
                            stm.executeUpdate(sql_vehicle);
                        }
                    }   
                }
                String sql_enter ="INSERT INTO enter VALUES('"+refno+"','"+nic+"','"+regno+"','"+date+"','"+milage+"','"+price+"')";
                stm.executeUpdate(sql_enter);
                JOptionPane.showMessageDialog(this,"Recorded adeed successfully");
               
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(Enter.class.getName()).log(Level.SEVERE, null, ex);
        }
                refnot.setText("");
                regnot.setText("");
                categoryt.setText("");
                maket.setText("YYYY");
                modelt.setText("");
                manuyt.setText("YYYY");
                regyt.setText("YYYY");
                milaget.setText("0000000");
                pricet.setText("");
                nict.setText("");
                namet.setText("");
                addresst.setText("");
                tpt.setText("077-1234567");
                datet.setText("YYYY-MM-DD");
                regnot.setText("XXX-xxx");
                regnot.requestFocus();
    }
    
    private void datetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datetKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            savevehicle();   
        }
    }//GEN-LAST:event_datetKeyPressed

    private void regnotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regnotKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            categoryt.requestFocus();
        }
        
    }//GEN-LAST:event_regnotKeyPressed

    private void categorytKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categorytKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            maket.requestFocus();
        }
    }//GEN-LAST:event_categorytKeyPressed

    private void maketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maketKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            modelt.requestFocus();
        }
         String myr = maket.getText();
        int length=myr.length();
        
        char c=evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<4){
                maket.setEditable(true);
            }
            else
            {
                maket.setEditable(false);
                text3.setText("Invalid entry");
               
                
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {  
                maket.setEditable(true);
            }
            else
            {
                maket.setEditable(false);
               text3.setText("*Can't add letters");
            }
        }
        

    }//GEN-LAST:event_maketKeyPressed

    private void modeltKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeltKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            manuyt.requestFocus();
        }
    }//GEN-LAST:event_modeltKeyPressed

    private void manuytKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manuytKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            regyt.requestFocus();
        }
       String myr = manuyt.getText();
        int length=myr.length();
        
        char c=evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<4){
                manuyt.setEditable(true);
            }
            else
            {
                manuyt.setEditable(false);
                text5.setText("Invalid entry");
                
                
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {  
                manuyt.setEditable(true);
            }
            else
            {
                manuyt.setEditable(false);
               text5.setText("*Can't add letters");
            }
        }
        
    }//GEN-LAST:event_manuytKeyPressed

    private void regytKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regytKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            milaget.requestFocus();
        }
        String myr = regyt.getText();
        int length=myr.length();
        
        char c=evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<4){
                regyt.setEditable(true);
            }
            else
            {
                regyt.setEditable(false);
                text6.setText("Invalid entry");
            
                
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {  
                regyt.setEditable(true);
            }
            else
            {
                regyt.setEditable(false);
               text6.setText("*Can't add letters");
            }
        }
    }//GEN-LAST:event_regytKeyPressed

    private void milagetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_milagetKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            pricet.requestFocus();
        }
    }//GEN-LAST:event_milagetKeyPressed

    private void pricetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricetKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            refnot.requestFocus();
        }
    }//GEN-LAST:event_pricetKeyPressed

    private void nictKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nictKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            namet.requestFocus();
        }
    }//GEN-LAST:event_nictKeyPressed

    private void nametKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            addresst.requestFocus();
        }
    }//GEN-LAST:event_nametKeyPressed

    private void addresstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addresstKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            tpt.requestFocus();
        }
    }//GEN-LAST:event_addresstKeyPressed

    private void tptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tptKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            datet.requestFocus();
        }
         String myr = regyt.getText();
        int length=myr.length();
        
        char c=evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<10){
                tpt.setEditable(true);
            }
            else
            {
                tpt.setEditable(false);
                text7.setText("Invalid entry");
                
                
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {  
                tpt.setEditable(true);
            }
            else
            {
                tpt.setEditable(false);
               text7.setText("*Can't add letters");
            }
        }
        
    }//GEN-LAST:event_tptKeyPressed

    private void manuytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manuytActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Welcome jf = new Welcome();
        jf.show();
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        savevehicle();
    }//GEN-LAST:event_saveMouseClicked

    private void regnotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnotFocusGained
       regnot.setText("");
        text1.setText("");
         
        if(regnot.getText().equals("XXX-xxxx")){
           regnot.setText(null);
           regnot.requestFocus();
            
       }
        
    }//GEN-LAST:event_regnotFocusGained

    private void regnotFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnotFocusLost
        if(regnot.getText().length()==0){
           FontStyle(regnot);
           regnot.setText("XXX-xxx");
       }
        if(regnot.getText().length()<7 || regnot.getText().length()>8){
           text1.setText("*Invalid entry");
          
        }
    }//GEN-LAST:event_regnotFocusLost

    private void maketFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maketFocusGained
        
        text3.setText("");
       
        if(maket.getText().equals("YYYY")){
           maket.setText(null);
           maket.requestFocus();
           
       }
    }//GEN-LAST:event_maketFocusGained

    private void maketFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maketFocusLost
        if(maket.getText().length()==0){
           FontStyle(maket); 
           maket.setText("YYYY");
       }
        text3.setText("");
          
        
         
        
    }//GEN-LAST:event_maketFocusLost

    private void manuytFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manuytFocusGained
       
        text5.setText("");
        if(manuyt.getText().equals("YYYY")){
           manuyt.setText(null);
           manuyt.requestFocus();

           
       }
        
    }//GEN-LAST:event_manuytFocusGained

    private void manuytFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manuytFocusLost
       if(manuyt.getText().length()==0){
           FontStyle(manuyt);
           manuyt.setText("YYYY");
       }
       text5.setText("");
       
    }//GEN-LAST:event_manuytFocusLost

    private void regytFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regytFocusGained
       
        text6.setText("");
        if(regyt.getText().equals("YYYY")){
           regyt.setText(null);
           regyt.requestFocus();
           
           
       }
    }//GEN-LAST:event_regytFocusGained

    private void regytFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regytFocusLost
        if(regyt.getText().length()==0){
            FontStyle(regyt);
           regyt.setText("YYYY");
       }
        text6.setText("");
    }//GEN-LAST:event_regytFocusLost

    private void milagetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_milagetFocusGained
        if(milaget.getText().equals("0000000")){
           milaget.setText(null);
           milaget.requestFocus();
           
           
       }
    }//GEN-LAST:event_milagetFocusGained

    private void milagetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_milagetFocusLost
       
    }//GEN-LAST:event_milagetFocusLost

    private void tptFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tptFocusGained
        text7.setText("");
        if(tpt.getText().equals("077-1234567")){
           tpt.setText(null);
           tpt.requestFocus();
          
           
       }
    }//GEN-LAST:event_tptFocusGained

    private void tptFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tptFocusLost
        if(tpt.getText().length()==0){
            FontStyle2(tpt);
           tpt.setText("077-1234567");
       }
        text7.setText("");
    }//GEN-LAST:event_tptFocusLost

    private void datetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datetFocusGained
         if(datet.getText().equals("YYYY-MM-DD")){
           datet.setText(null);
           datet.requestFocus();
           
           
       }
    }//GEN-LAST:event_datetFocusGained

    private void datetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datetFocusLost
        if(datet.getText().length()==0){
            FontStyle2(datet);
           datet.setText("YYYY-MM-DD");
       }
    }//GEN-LAST:event_datetFocusLost

    private void refnotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refnotFocusGained
         autorefNo();
       
    }//GEN-LAST:event_refnotFocusGained

    private void refnotFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_refnotFocusLost

        if(refnot.getText().length()==0){
            FontStyle2(refnot);
            refnot.setText("C0000");
        }
        
            
    }//GEN-LAST:event_refnotFocusLost

    private void refnotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_refnotKeyPressed
         if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            nict.requestFocus();
        }
    }//GEN-LAST:event_refnotKeyPressed

    private void regnotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regnotMouseClicked
        text1.setText("");
    }//GEN-LAST:event_regnotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresst;
    private javax.swing.JTextField categoryt;
    private javax.swing.JTextField datet;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maket;
    private javax.swing.JTextField manuyt;
    private javax.swing.JTextField milaget;
    private javax.swing.JTextField modelt;
    private javax.swing.JTextField namet;
    private javax.swing.JTextField nict;
    private javax.swing.JTextField pricet;
    private javax.swing.JTextField refnot;
    private javax.swing.JTextField reftext;
    private javax.swing.JTextField regnot;
    private javax.swing.JTextField regyt;
    private javax.swing.JLabel save;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField tpt;
    // End of variables declaration//GEN-END:variables
}
